CREATE TABLE Funcionarios (
	CODFUN		SMALLINT PRIMARY KEY IDENTITY NOT NULL
,	Nome		VARCHAR(15) NOT NULL
,	Sobrenome	VARCHAR(15) NOT NULL
,	DataNasc	DATE		NOT	NULL
,	DataContr	DATE		NOT NULL
,	Email		VARCHAR(30)
,	CODCAR		INT			NOT NULL
)